INSERT INTO area VALUES("CARDIOLOGIA",25,0,0);
INSERT INTO area VALUES("ODONTOLOGIA",20,0,0);
INSERT INTO area VALUES("PEDIATRIA",15,0,0);
INSERT INTO area VALUES("LABORATORIO",35,0,0);
INSERT INTO area VALUES("FARMACIA",30,0,0);